package lk.aora.equipmentmanagement.entity;

public enum AuditAction {
    CREATE_EQUIPMENT,
    UPDATE_EQUIPMENT,
    RETIRE_EQUIPMENT,
    CREATE_USER,
    UPDATE_USER,
    CREATE_WORKSITE,
    UPDATE_WORKSITE,
    ASSIGN_SITE_ADMIN,
    ASSIGN_STORE_MANAGER,
    CREATE_TRANSFER,
    UPDATE_TRANSFER,
    COMPLETE_TRANSFER,
    CANCEL_TRANSFER,
    DELETE_TRANSFER,
    CREATE_MAINTENANCE,
    UPDATE_MAINTENANCE,
    LOGIN_RELATED_SECURITY_EVENTS
}
